### ISSUE TITLE
Failed to load resource parsley.js.map

### ISSUE THREAD

**Issue by Pogoss** [jiripospisil/parsley-rails#25]
Running on ruby 2.3.1, rails 4.0.1
Install correctly gem, but after reloading server get an error
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:3000/assets/parsley.js.map

**Comment by afhammad** [comment]
+1

**Comment by patricklindsay** [comment]
This is because Parsley is trying to load the source mappings which are not required for the end user (and not present in this gem).

[This line](https://github.com/jiripospisil/parsley-rails/blob/master/vendor/assets/javascripts/parsley.js#L2387) and [this line](https://github.com/jiripospisil/parsley-rails/blob/master/vendor/assets/javascripts/parsley.min.js#L18) needs to be removed in order to stop the 404s.

@jiripospisil What do you think? Would you be happy to accept a PR removing these lines? (and removing them in future version updates)

**Comment by jiripospisil** [comment]
Actually I think we should just add the .map files to the gem. It could be useful to see the original source code (before babel gets its hands all over it) while debugging some potential problems with Parsley itself. I will add them in the PR I'm working on (updating to 2.7.0).

**Comment by jiripospisil** [comment]
I've opened a PR which updates Parsley version to 2.7.0, adds the maps and extras. You can try it out if you want. I will release a new version of the gem some time tomorrow.

```
gem 'parsley-rails', github: 'jiripospisil/parsley-rails', branch: 'release_270'
```
